version: '3.1'

services:
  proxy:
    container_name: proxy
    build: 
      context: .
      dockerfile: Dockerfile
    image: modsec-sentinel:latest
    environment:
      WORKSPACE_ID: <your workspace id>
      WORKSPACE_SHARED_KEY: <your shared access key>
    volumes:
      - ./modsec-nginx/nginx/conf.d:/etc/nginx/conf.d/
      - ./modsec-nginx/nginx/ssl:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
  sampleserver:
    container_name: sampleserver
    image: mcr.microsoft.com/dotnet/samples:aspnetapp